org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

mod_version=0.1.0-beta
maven_group=com.routinize

fabric_api_version=0.155.2+26.1.2
modmenu_version=21.0.0-alpha.1